# Generated by Django 4.2.1 on 2023-06-05 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_article', models.CharField(blank=True, max_length=50, null=True)),
                ('quantité_total', models.IntegerField(blank=True, default=0, null=True)),
                ('quantité_émise', models.IntegerField(blank=True, default=0, null=True)),
                ('quantité_reçu', models.IntegerField(blank=True, default=0, null=True)),
                ('prix_unitaire', models.IntegerField(blank=True, default=0, null=True)),
                ('nom_categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application1.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantité', models.IntegerField(blank=True, default=0, null=True)),
                ('montant_reçu', models.IntegerField(blank=True, default=0, null=True)),
                ('délivré_A', models.CharField(blank=True, max_length=50, null=True)),
                ('prix_unitaire', models.IntegerField(blank=True, default=0, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application1.produit')),
            ],
        ),
    ]
