# Generated by Django 4.2.1 on 2023-06-23 21:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Application1", "0002_alter_categorie_id_alter_produit_id_alter_vente_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produit",
            old_name="quantité_reçu",
            new_name="quantite_emise",
        ),
        migrations.RenameField(
            model_name="produit",
            old_name="quantité_total",
            new_name="quantite_obtenue",
        ),
        migrations.RenameField(
            model_name="produit",
            old_name="quantité_émise",
            new_name="quantite_total",
        ),
        migrations.RenameField(
            model_name="vente",
            old_name="délivré_A",
            new_name="delivre_A",
        ),
        migrations.RenameField(
            model_name="vente",
            old_name="montant_reçu",
            new_name="montant_obtenue",
        ),
        migrations.RenameField(
            model_name="vente",
            old_name="quantité",
            new_name="quantite",
        ),
    ]
